name: Minify Workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install minify
        run: sudo apt-get install -y minify

      - name: Minify Javascript
        run: minify -o basemap-tiles.min.js basemap-tiles.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Minify source code